import React, { useState } from 'react';
import { Copy, Check, Download, Clock, User, FileText, Zap } from 'lucide-react';
import { clsx } from 'clsx';

const typeColors = {
  blog:     { bg: 'bg-violet-50',  text: 'text-violet-600' },
  tweet:    { bg: 'bg-sky-50',     text: 'text-sky-600'    },
  linkedin: { bg: 'bg-indigo-50',  text: 'text-indigo-600' },
  email:    { bg: 'bg-purple-50',  text: 'text-purple-600' },
};

export default function ContentDisplay({ content }) {
  const [copied, setCopied] = useState(false);

  if (!content) return null;

  const { bg, text } = typeColors[content.contentType] || typeColors.blog;

  const handleCopy = () => {
    navigator.clipboard.writeText(content.generatedContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownload = () => {
    const a = document.createElement('a');
    a.href = URL.createObjectURL(new Blob([content.generatedContent], { type: 'text/plain' }));
    a.download = `${content.topic.slice(0, 30)}.txt`;
    a.click();
  };

  const wordCount = content.generatedContent.split(/\s+/).filter(Boolean).length;

  return (
    <div className="animate-fade-up space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div className="space-y-2 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <span className={clsx('badge', bg, text)}>{content.contentType}</span>
            <span className="badge bg-[#f4f3f2] text-[#4a4455]">{content.tone}</span>
            <span className="badge bg-[#f4f3f2] text-[#4a4455] flex items-center gap-1">
              <User className="w-3 h-3" />{content.audience}
            </span>
          </div>
          <h2 className="text-xl font-bold text-[#1a1c1c] leading-snug line-clamp-2">
            {content.topic}
          </h2>
        </div>
      </div>

      {/* Actions */}
      <div className="flex items-center gap-3">
        <button
          onClick={handleCopy}
          className={clsx(
            'flex-1 py-3.5 rounded-2xl flex items-center justify-center gap-2 text-sm font-semibold transition-all duration-300',
            copied
              ? 'bg-emerald-50 text-emerald-600 shadow-[0_4px_16px_-4px_rgba(16,185,129,0.2)]'
              : 'bg-[#f4f3f2] text-[#1a1c1c] hover:bg-[#ede0ff] hover:text-[#630ed4]'
          )}
        >
          {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
          {copied ? 'Copied!' : 'Copy'}
        </button>
        <button
          onClick={handleDownload}
          className="py-3.5 px-5 rounded-2xl bg-[#f4f3f2] text-[#1a1c1c] hover:bg-[#ede0ff] hover:text-[#630ed4] text-sm font-semibold transition-all flex items-center gap-2"
        >
          <Download className="w-4 h-4" />
          Save
        </button>
      </div>

      {/* Content Box */}
      <div className="relative">
        <div className="absolute -inset-0.5 rounded-[1.5rem] bg-gradient-to-br from-violet-100/60 to-indigo-100/40 blur-sm" />
        <div className="relative bg-white rounded-[1.4rem] p-8 space-y-1 shadow-mist overflow-hidden">
          <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-bl from-violet-50 to-transparent rounded-bl-[3rem]" />
          <div className="whitespace-pre-wrap text-[0.95rem] leading-[1.8] text-[#1a1c1c] font-normal relative z-10">
            {content.generatedContent}
          </div>
        </div>
      </div>
      
      {/* Footer meta */}
      <div className="flex items-center justify-between text-xs text-[#7b7487] font-medium px-1">
        <span className="flex items-center gap-1.5">
          <Zap className="w-3.5 h-3.5 text-[#7c3aed]" />
          Generated by Gemini 2.5 Flash
        </span>
        <span className="flex items-center gap-3">
          <span>{wordCount} words</span>
          <span className="flex items-center gap-1">
            <Clock className="w-3.5 h-3.5" />
            {new Date(content.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </span>
        </span>
      </div>
    </div>
  );
}
